version: 2
jobs:
  build:
    docker:
      - image: osrf/ros:melodic-ros-core-bionic
    steps:
      - checkout:
          path: src
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -qq -y cmake libgazebo9-dev python3 python3-dev python3-pip python3-nose
            sudo pip3 install catkin_tools numpy pybind11 rospkg
      - run:
          name: Build workspace
          command: |
            source /opt/ros/melodic/setup.bash
            catkin init
            catkin config --cmake-args -DPYTHON_EXECUTABLE=$(which python3)
            catkin build -j2 --no-status --cmake-args -DCMAKE_BUILD_TYPE:STRING=Debug
      - run:
          name: Run tests
          command: |
            source devel/setup.bash
            catkin run_tests gazebo_server -j1 --no-deps --no-status
            catkin_test_results build
