version: 2
jobs:
  build:
    docker:
      - image: mvukov/gazebo-server-ci:latest
    steps:
      - checkout:
          path: src
      - run:
          name: Build workspace
          command: |
            source /opt/ros/melodic/setup.bash
            catkin init
            catkin config --cmake-args -DPYTHON_EXECUTABLE=$(which python3)
            catkin build -j2 --no-status --cmake-args -DCMAKE_BUILD_TYPE:STRING=Debug
      - run:
          name: Run tests
          command: |
            source /opt/ros/melodic/setup.bash
            source devel/setup.bash
            catkin run_tests gazebo_server -j1 --no-deps --no-status
            catkin_test_results build
